### ISSUE TITLE
Trouble Following Example

### ISSUE THREAD

**Issue by vfr292** [filepreviews/filepreviews-python#4]
Hi,

I'm trying to follow the example, albeit with my API Key and Secret and I get the following error:

```
Traceback (most recent call last):
  File "/Users/Victor/Documents/Python/Post_Great_Pics/src/scripts/filepreviews_v2_test", line 6, in <module>
    response = fp.generate('http://www.getblimp.com/images/screenshot1.png')
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/filepreviews/api.py", line 49, in generate
    response = self.client.post('previews', data=params)
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/filepreviews/client.py", line 77, in post
    return self.request('POST', *args, json=data)
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/filepreviews/client.py", line 18, in request
    session_response = self.session.request(method, url, **kwargs)
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Victor/Documents/Python/Post_Great_Pics/pgp_venv/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(60, 'Operation timed out'))
```

Here is my code:

```
from filepreviews import FilePreviews

fp = FilePreviews(api_key='X', api_secret='Y')
response = fp.generate('http://www.getblimp.com/images/screenshot1.png')
print response
```

**Comment by jpadilla** [comment]
@vfr292 good catch, sorry about that. Just released v2.0.1 with that fixed.
